import {test,expect} from '@playwright/test';import path from 'node:path';import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..'),owner='11111111-1111-4111-8111-111111111111';
async function loggedIn(page){await page.addInitScript(({owner})=>{localStorage.setItem('sb-muhxebuwucyknvdmdzsh-auth-token',JSON.stringify({access_token:'test-jwt',refresh_token:'test-refresh',expires_at:Math.floor(Date.now()/1000)+7200,expires_in:7200,token_type:'bearer',user:{id:owner,email:'test@example.invalid',aud:'authenticated',role:'authenticated'}}));},{owner});}
test('registration atomically queues evidence, retries same UUID, compacts blobs and withdraws',async({page})=>{
 await loggedIn(page);let beginCalls=0,fail=true,payload,withdraw=0;
 await page.route('**/functions/v1/collect',async route=>{const b=route.request().postDataJSON();if(b.action==='identity')return route.fulfill({json:{admin:false}});if(b.action==='begin'){beginCalls++;payload=b.payload;if(fail)return route.fulfill({status:503,json:{error:'temporary offline'}});return route.fulfill({json:{status:'pending',uploads:b.payload.images.map(i=>({kind:i.kind,path:`${owner}/${b.payload.client_record_id}/${i.kind}.png`,token:'test-signature'}))}});}if(b.action==='withdraw')withdraw++;return route.fulfill({json:{status:'complete'}});});
 await page.route('**/storage/v1/object/upload/sign/**',route=>route.fulfill({json:{Key:'saved'}}));
 await page.goto('./');await page.locator('#raid-boss').selectOption({label:'루이'});await page.locator('#raid-memo').fill('DO_NOT_TRANSMIT');
 await page.locator('#screenshot').setInputFiles(path.join(root,'tests/fixtures/KakaoTalk_20261002_135728198.jpg'));await expect(page.locator('#progress')).toHaveText(/템플릿 33개/,{timeout:120000});await page.locator('#collection-consent').check();await page.locator('#save-raid').click();
 await page.locator('[data-tab="cloud"]').click();await expect(page.locator('tbody')).toContainText('temporary offline');expect(beginCalls).toBe(1);const id=payload.client_record_id;expect(JSON.stringify(payload)).not.toContain('DO_NOT_TRANSMIT');expect(payload.boss).toBe('루이');expect(payload.images.map(x=>x.kind)).toEqual(['original','annotated']);expect(payload.rewards.every(x=>x.box!==null)).toBe(true);
 fail=false;await page.locator('#retry-cloud').click();await expect(page.locator('tbody')).toContainText('제출 완료');expect(payload.client_record_id).toBe(id);
 const stored=await page.evaluate(()=>new Promise(resolve=>{const r=indexedDB.open('cat-hero-ledger',1);r.onsuccess=()=>{const g=r.result.transaction('outbox').objectStore('outbox').getAll();g.onsuccess=()=>resolve(g.result);};}));expect(stored[0].blobs).toBeNull();
 page.on('dialog',d=>d.accept());await page.locator('[data-tab="records"]').click();await page.locator('[data-delete-raid]').click();await page.locator('[data-tab="cloud"]').click();await expect(page.locator('tbody')).toContainText('철회 완료');expect(withdraw).toBe(1);
});
test('legacy localStorage migrates without creating historic submissions',async({page})=>{await page.goto('./');const seed=await page.evaluate(async()=>await(await fetch('seed.json')).json());seed.members[0].name='기존 참여자';await page.evaluate(seed=>{localStorage.setItem('cat-hero-boss-reward-v1',JSON.stringify(seed));},seed);await page.reload();await page.locator('[data-tab="members"]').click();await expect(page.locator('[data-member-name="1"]')).toHaveValue('기존 참여자');await page.locator('[data-tab="cloud"]').click();await expect(page.locator('tbody')).toContainText('아직 데이터가 없습니다.');});
