import '@fontsource/noto-sans-kr/korean-400.css';
import '@fontsource/noto-sans-kr/korean-600.css';
import '@fontsource/noto-sans-kr/400.css';
import '@fontsource/noto-sans-kr/600.css';
import './style.css';
import * as XLSX from 'xlsx';
import {EXCEL_COLUMNS,summarize,validateName,deleteMember,validateState} from './domain.js';
import {imageCanvas,recognize} from './vision.js';
import {readState,saveState,jobs,putJob} from './outbox.js';
import {cloud,session,initCloud,api,pump} from './cloud.js';
import {annotate} from './annotation.js';
import {collectionPayload,sha256,NOTICE_VERSION} from './cloud-payload.js';
const KEY='cat-hero-boss-reward-v1',base=new URL(import.meta.env.BASE_URL, document.baseURI).href;
const $=s=>document.querySelector(s),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=x=>x===null||x===undefined?'—':Number(x).toLocaleString('ko-KR',{maximumFractionDigits:4});
const nextId=items=>Math.max(0,...items.map(x=>x.id))+1;
const localDate=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
let seed,state,tab='raid',draft=[],busy=false,sourceName='',rangeFrom='',rangeTo='',sourceFile=null,sourceCanvas=null,saving=false;
let queue=[],isAdmin=false,adminRows=[],adminDetail=null,cloudError='',adminBefore='',adminBoss='',adminReview='';
let raidForm={date:localDate(),time:new Date().toTimeString().slice(0,5),boss:'',memo:'',members:[]};
const tabs=[['raid','보스전 등록','01'],['summary','정산 장부','02'],['records','보스전 기록','03'],['members','참여자 관리','04'],['rewards','보상 마스터','05'],['settings','설정 · 백업','06'],['cloud','수집 계정 · 전송','07'],['admin','관리자 수집함','08']];
async function mutate(fn,job){if(saving){toast('저장 중입니다. 잠시 기다려 주세요.');return false;}saving=true;const before=structuredClone(state);try{fn();validateState(state,seed);document.querySelectorAll('button,input,select').forEach(el=>el.disabled=true);await saveState(state,job);saving=false;render();toast('저장했습니다.');return true;}catch(e){state=before;saving=false;render();toast(`저장 실패: ${e.message}`,true);return false;}finally{saving=false;}}
async function refreshCloud(){const next=await jobs(),changed=JSON.stringify(next)!==JSON.stringify(queue);queue=next;if(state&&changed&&!busy&&!saving&&['cloud','records'].includes(tab))render();}
async function identity(){isAdmin=false;if(session)try{isAdmin=(await api('identity')).admin;cloudError='';}catch(e){cloudError=e.message;}await refreshCloud();if(state&&!busy&&!saving)render();pump(refreshCloud);}
function toast(text,error=false){const el=$('#toast');el.textContent=text;el.className=`toast visible ${error?'error':''}`;clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>el.classList.remove('visible'),6000);}
function table(headers,rows){return `<div class="table-scroll"><table><thead><tr>${headers.map(x=>`<th>${esc(x)}</th>`).join('')}</tr></thead><tbody>${rows.join('')||`<tr><td colspan="${headers.length}" class="empty">아직 데이터가 없습니다.</td></tr>`}</tbody></table></div>`;}
function render(){
  raidForm.members=raidForm.members.filter(id=>state.members.some(m=>m.id===id&&m.active));
  $('#app').innerHTML=`<aside><div class="brand"><span class="logo">C</span><div>CAT HERO<small>BOSS REWARD LEDGER</small></div></div><div class="nav-caption">WORKSPACE</div><nav>${tabs.map(([id,label,no])=>`<button data-tab="${id}" class="${tab===id?'selected':''}"><span>${no}</span>${label}</button>`).join('')}</nav><div class="aside-note"><span class="dot"></span>브라우저에 저장됨<p>${session?'로그인됨 · 이미지 기록 자동 제출':'로그인 전에는 로컬 기록만 저장'}<br>정산 장부는 이 기기에 보관됩니다.</p></div></aside>
  <main><header><div><div class="eyebrow">GUILD OPERATIONS / U01—U33</div><h1>${esc(tabs.find(t=>t[0]===tab)[1])}</h1></div><span class="badge">WEB EDITION · v1.2</span></header>
  <div class="mapping-note">픽뽑 · 픽업 → 전설픽업 &nbsp; / &nbsp; 룬 → 룬 소환 &nbsp; / &nbsp; 동 → 동료소환 &nbsp; / &nbsp; 빨레 · 보 → 정산 제외</div>
  <div id="content">${tab==='raid'?raidView():tab==='summary'?summaryView():tab==='records'?recordsView():tab==='members'?membersView():tab==='rewards'?rewardsView():tab==='settings'?settingsView():tab==='cloud'?cloudView():adminView()}</div>
  <footer>CAT HERO · 설치형과 같은 U01~U33 매핑 / 균등 분배 / 엑셀 환산 구조</footer></main><div id="toast" class="toast" role="status"></div>`;
  bind();
}
function raidView(){return `<section class="panel"><div class="section-heading"><h2>처치 기록</h2><span>STEP 01</span></div><div class="form-grid"><label>날짜<input id="raid-date" type="date" value="${esc(raidForm.date)}" required></label><label>시간<input id="raid-time" type="time" value="${esc(raidForm.time)}" required></label><label>보스<select id="raid-boss">${state.bosses.map(b=>`<option ${b===raidForm.boss?'selected':''}>${esc(b)}</option>`).join('')}</select></label><label>메모<input id="raid-memo" value="${esc(raidForm.memo)}" placeholder="선택 사항"></label></div><div class="section-heading participants"><h3>참여자</h3><span id="member-count">${raidForm.members.length}명 · 자동 균등 분배</span></div><div class="member-chips">${state.members.filter(m=>m.active).map(m=>`<label><input type="checkbox" data-member="${m.id}" ${raidForm.members.includes(m.id)?'checked':''}>${esc(m.name)}</label>`).join('')||'<p>참여자 관리에서 활성 참여자를 추가해 주세요.</p>'}</div></section>
  <section class="panel"><p class="collection-notice">${session?'정산 등록 시 보상 기록과 원본·마킹 이미지를 관리자에게 자동 제출합니다. 이미지 안의 닉네임도 포함될 수 있습니다.':'현재 로컬 저장 모드입니다. 관리자 자동 제출은 수집 계정 로그인 후 새로 등록한 이미지 기록부터 적용됩니다.'} ${session?`<label><input id="collection-consent" type="checkbox" ${state.collection_notice===NOTICE_VERSION?'checked':''}> 원본 이미지 포함 자동 제출 안내 확인</label>`:''}</p><div class="section-heading"><h2>이미지 인식</h2><span>STEP 02</span></div><label class="upload-zone"><span class="upload-icon">＋</span><strong>처치 결과 스크린샷 선택</strong><span>PNG · JPG / 카드 검출 → 보상 매칭 → 숫자 인식</span><input id="screenshot" type="file" accept="image/png,image/jpeg" ${busy?'disabled':''}></label><p id="progress" class="status">${busy?'인식 중...':'템플릿 33개 연결 · 인식 후 보상과 수량을 확인해 주세요.'}</p>
  <h3>수기로 보상 입력</h3><form id="manual-reward-form"><div class="form-grid"><label>입력한 보상 단어<input name="word" placeholder="예: 픽뽑, 룬, 보레" maxlength="80" required></label><label>수량<input name="quantity" type="number" min="0" step="1" value="1" required></label><label>연결할 보상 마스터<select name="reward_id" required><option value="">직접 선택해 주세요</option>${state.rewards.filter(r=>r.enabled).map(r=>`<option value="${r.id}">${esc(r.name)}</option>`).join('')}</select></label></div><button ${busy?'disabled':''}>수기 보상 추가</button></form><p class="hint">입력한 단어를 보상 마스터에 직접 연결합니다. 이미지 없이 정산 등록할 수 있으며, 이미지 없는 기록은 개인 장부에만 저장됩니다.</p>
  <div class="section-heading"><h3>보상 확인 / 수동 매칭</h3><button id="add-row" class="secondary" ${busy?'disabled':''}>보상 직접 추가</button></div>
  ${table(['카드','보상','수량','OCR 수량','인식점수','후보ID','수량신뢰도','등급 / 상태',''],draft.map((r,i)=>`<tr><td>${r.thumbnail?`<img class="card-thumb" src="${r.thumbnail}" alt="카드 ${i+1}">`:'—'}</td><td><select data-reward="${i}" ${busy?'disabled':''}><option value="">미지정</option>${state.rewards.filter(x=>x.enabled||x.id===r.reward_id).map(x=>`<option value="${x.id}" ${x.id===r.reward_id?'selected':''}>${esc(x.name)}${x.enabled?'':' (비활성)'}</option>`).join('')}</select><small>${r.input_word?`입력 단어: ${esc(r.input_word)}`:`후보: ${esc(r.candidate_name||'—')}`}</small></td><td><input type="number" min="0" step="1" value="${r.quantity}" data-qty="${i}" ${busy?'disabled':''}></td><td>${fmt(r.ocr_quantity)}</td><td>${r.score==null?'—':r.score.toFixed(3)}</td><td>${esc(r.candidate_id||'—')}</td><td>${r.quantity_confidence==null?'—':r.quantity_confidence.toFixed(3)}</td><td><span class="rarity ${esc(r.rarity)}">${esc(r.rarity||'수동')}</span><small>${esc(r.match_status||'직접 입력')}</small><small>${esc(r.quantity_status||'')}</small></td><td><button data-remove="${i}" class="danger quiet" ${busy?'disabled':''}>삭제</button></td></tr>`))}
  <div class="action-row"><span>${draft.length}개 보상 · ${esc(sourceName||'직접 입력 가능')}</span><button id="save-raid" ${busy?'disabled':''}>정산 등록</button></div></section>`;}
function summaryView(){const rows=summarize(state,rangeFrom,rangeTo||'9999-12-31'),value=rows.reduce((a,r)=>a+r.합산가치,0),cash=rows.reduce((a,r)=>a+r['수수료 제외'],0);return `<div class="metrics"><div><span>합산 보라가치</span><strong>${fmt(value)}</strong></div><div><span>수수료 제외 현금</span><strong>₩ ${fmt(cash)}</strong></div><div><span>정산 참여자</span><strong>${rows.length}<small>명</small></strong></div></div><section class="panel"><div class="section-heading"><h2>개인별 누적 장부</h2><button id="export-xlsx">Excel 다운로드</button></div><div class="date-range"><label>시작일<input id="from" type="date" value="${rangeFrom}"></label><label>종료일<input id="to" type="date" value="${rangeTo}"></label><button id="filter" class="secondary">기간 적용</button></div>${table(['참여자',...EXCEL_COLUMNS,'합산가치','현금','수수료 제외'],rows.map(r=>`<tr><td>${esc(r.member)}</td>${[...EXCEL_COLUMNS,'합산가치','현금','수수료 제외'].map(k=>`<td>${fmt(r[k])}</td>`).join('')}</tr>`))}<p class="hint">보상 값어치와 분배 방식 변경은 기존 기록의 합계에도 반영됩니다. 빨레/보는 기록에 보관하고 합산에서 제외합니다.</p></section>`;}
function recordsView(){return `<section class="panel"><div class="section-heading"><h2>원본 보스전 기록</h2><span>${state.raids.length} RAIDS</span></div>${table(['ID','날짜 / 시간','보스','참여자','보상 · 수량','메모','전송 상태',''],[...state.raids].reverse().map(r=>`<tr><td>#${r.id}</td><td>${esc(r.date)}<small>${esc(r.time)}</small></td><td>${esc(r.boss)}</td><td>${r.member_ids.map(id=>esc(state.members.find(m=>m.id===id)?.name)).join(', ')}</td><td>${r.rewards.map(x=>`${esc(x.reward_name)} × ${fmt(x.quantity)}`).join('<br>')}</td><td>${esc(r.memo)}</td><td>${esc(queueLabel(r.client_record_id))}</td><td><button class="danger quiet" data-delete-raid="${r.id}">삭제</button></td></tr>`))}</section>`;}
function membersView(){return `<section class="panel"><div class="section-heading"><h2>참여자 추가</h2><span>MEMBERS</span></div><form id="member-add" class="inline-form"><input name="name" placeholder="참여자 이름" required maxlength="80"><button>참여자 추가</button></form></section><section class="panel"><h2>참여자 관리</h2><p class="hint">비활성화하면 다음 보스전의 참여자 목록에서 제외됩니다. 기존 정산 기록은 유지됩니다.</p>${table(['ID','이름','상태',''],state.members.map(m=>`<tr><td>${m.id}</td><td><input data-member-name="${m.id}" value="${esc(m.name)}" maxlength="80"></td><td><label class="toggle"><input data-member-active="${m.id}" type="checkbox" ${m.active?'checked':''}>활성</label></td><td><button data-save-member="${m.id}" class="secondary">저장</button> <button data-delete-member="${m.id}" class="danger quiet">삭제</button></td></tr>`))}</section>`;}
function rewardsView(){return `<section class="panel"><div class="section-heading"><h2>보상 정보 / 값어치</h2><span>MASTER DATA</span></div><p class="hint">U01~U33 연결과 정산 컬럼은 고정합니다. 비활성 보상도 후보로 인식되며, 신규 정산에는 활성 보상만 등록할 수 있습니다.</p>${table(['보상명','정산 컬럼 / 후보ID','값어치','수량 방식','분배 방식','활성',''],state.rewards.map(r=>`<tr><td><input data-r-name="${r.id}" value="${esc(r.name)}" maxlength="80"></td><td>${esc(r.settlement_column==='__EXCLUDE__'?'정산 제외':r.settlement_column)}<small>${state.templates.filter(t=>t.reward_id===r.id).map(t=>esc(t.candidate_id)).join(' · ')}</small></td><td><input data-r-value="${r.id}" type="number" min="0" step="any" value="${r.unit_value}"></td><td><select data-r-mode="${r.id}">${['AUTO','OCR','DEFAULT_ONE'].map(m=>`<option ${m===r.quantity_mode?'selected':''}>${m}</option>`).join('')}</select></td><td><select data-r-dist="${r.id}">${['EQUAL','PER_PERSON'].map(m=>`<option value="${m}" ${m===r.distribution_type?'selected':''}>${m==='EQUAL'?'균등 분배':'인당 수량'}</option>`).join('')}</select></td><td><input data-r-enabled="${r.id}" type="checkbox" ${r.enabled?'checked':''}></td><td><button data-save-reward="${r.id}" class="secondary">저장</button></td></tr>`))}<p class="hint">소환권/랜덤 룬의 초기 값어치는 원본 프로젝트의 0을 유지했습니다. 필요하면 이 표에서 수정할 수 있습니다.</p></section>`;}
function settingsView(){return `<section class="panel"><h2>환산 / 인식 기준</h2><form id="settings-form"><div class="form-grid"><label>보라가치 100당 현금<input name="cash" type="number" min="0" step="any" value="${state.settings.cash_per_100_value}" required></label><label>수수료율 (0~1)<input name="fee" type="number" min="0" max="1" step="0.01" value="${state.settings.fee_rate}" required></label><label>자동매칭 기준 (0.50~0.99)<input name="threshold" type="number" min="0.5" max="0.99" step="0.01" value="${state.settings.match_threshold}" required></label></div><button>설정 저장</button></form></section><section class="panel"><h2>보스 추가</h2><form id="boss-add" class="inline-form"><input name="name" placeholder="새 보스 이름" required><button>보스 추가</button></form></section><section class="panel"><h2>데이터 백업 / 복원</h2><p>웹형 데이터는 현재 브라우저에 저장됩니다. 다른 기기에서는 JSON 백업을 불러와 이어서 사용하세요.</p><div class="backup-actions"><button id="backup">JSON 백업 다운로드</button><label class="file-button secondary">JSON 백업 복원<input id="restore" type="file" accept=".json,application/json"></label></div><p class="hint">복원은 현재 웹형 데이터를 교체합니다. 설치형 SQLite 데이터와 자동 동기화되지는 않습니다.</p><p class="hint">설치형은 저장소 ZIP을 내려받은 뒤 install.bat → run.bat 순서로 실행하세요. 기존 설치를 업데이트할 때 data/settlement.db를 먼저 백업하고 그대로 유지하세요.</p><a href="https://github.com/ryemso/cat_hero_boss_reward" target="_blank" rel="noopener">GitHub에서 설치형 받기 ↗</a></section>`;}
function queueLabel(id){const j=queue.find(x=>x.id===id);return !j?'로컬 기록':j.action==='withdraw'?(j.state==='complete'?'철회 완료':'철회 대기'):j.state==='complete'?'제출 완료':j.state==='failed'?'확인 필요':'전송 대기';}
function cloudView(){return `<section class="panel"><h2>수집 계정</h2><p>정산 등록과 동시에 원본 이미지·마킹 이미지·보상 기록을 관리자 수집함으로 자동 제출합니다. 정산 장부, 참여자 이름, 메모, 개인 단가는 이 기기에 남습니다. 이미지에 보이는 닉네임은 함께 전송될 수 있습니다.</p>${session?`<p>로그인: ${esc(session.user.email)} · ${isAdmin?'관리자':'일반 사용자'}</p><button id="signout" class="secondary">로그아웃</button>`:`<form id="cloud-login"><div class="form-grid"><label>이메일<input name="email" type="email" autocomplete="email" required></label><label>비밀번호<input name="password" type="password" autocomplete="current-password" minlength="8" required></label></div><div class="action-row"><button name="mode" value="signin">로그인</button><button name="mode" value="signup" class="secondary">이메일 계정 만들기</button></div></form><p class="hint">Supabase 대시보드 계정과 앱 수집 계정은 별개입니다. 회원가입 후 이메일 인증이 필요합니다.</p>`}<p class="hint">${esc(cloudError)}${session&&!isAdmin?' 관리자 지정은 앱 계정의 UUID를 확인한 뒤 프로젝트에서 설정합니다.':''}</p>${session?`<small>앱 계정 UUID: ${esc(session.user.id)}</small>`:''}</section><section class="panel"><div class="section-heading"><h2>자동 전송 대기열</h2><button id="retry-cloud" class="secondary">실패 기록 재시도</button></div>${table(['기록 ID','상태','최근 오류'],queue.map(j=>`<tr><td>${esc(j.id)}</td><td>${esc(queueLabel(j.id))}${session&&j.owner_id!==session.user.id?'<small>다른 계정 로그인 필요</small>':''}</td><td>${esc(j.error||'—')}</td></tr>`))}<p class="hint">통신 실패 시 자동 재시도합니다. 브라우저를 닫으면 전송이 중단되며 다시 열 때 이어갑니다. 제출 완료 후 이 기기의 대기열에서는 이미지 파일을 비웁니다. JSON 백업에는 이미지가 포함되지 않습니다.</p></section>`;}
function adminView(){if(!session||!isAdmin)return `<section class="panel"><h2>관리자 로그인 필요</h2><p>수집 계정에서 로그인하세요. 등록된 관리자만 전체 기록과 원본 이미지를 볼 수 있습니다.</p></section>`;
 return `<section class="panel"><div class="section-heading"><h2>관리자 수집함</h2><button id="admin-refresh">조회</button></div><div class="form-grid"><label>보스<input id="admin-boss" value="${esc(adminBoss)}" placeholder="전체"></label><label>검토 상태<select id="admin-status">${['','unreviewed','accepted','duplicate','rejected'].map(x=>`<option value="${x}" ${x===adminReview?'selected':''}>${esc(x||'전체')}</option>`).join('')}</select></label></div>${table(['접수 시각','보스 / 처치일','인원','보상','검토',''],adminRows.map(r=>`<tr><td>${esc(new Date(r.created_at).toLocaleString())}</td><td>${esc(r.payload.boss)}<small>${esc(r.payload.date)} ${esc(r.payload.time)}</small></td><td>${r.payload.participant_count}</td><td>${r.payload.rewards.length}개</td><td>${esc(r.status==='withdrawn'?'철회':r.review_status)}</td><td>${r.status==='complete'?`<button data-evidence="${r.id}" class="secondary">이미지 / 상세</button>`:''}</td></tr>`))}<div class="action-row"><button id="admin-more" class="secondary">다음 100건</button><button id="admin-export" class="secondary">현재 조회 CSV</button></div></section>${adminDetail?adminDetailView():''}`;
}
function adminDetailView(){const d=adminDetail,s=d.submission;return `<section class="panel"><h2>${esc(s.payload.boss)} · ${esc(s.payload.date)} · 상세</h2><p>동일 원본 해시 기록: ${d.duplicates.length}건 (자동 중복 제외하지 않음)</p><div class="evidence-images">${d.images.map(i=>`<figure><figcaption>${i.kind==='original'?'원본 이미지':'마킹 이미지'}</figcaption><img src="${esc(i.url)}" alt="${esc(i.kind)} 이미지"></figure>`).join('')}</div>${table(['보상키','확정 수량','후보ID','인식점수','OCR 수량','수량신뢰도','수정'],s.payload.rewards.map(r=>`<tr><td>${esc(r.reward_key)}</td><td>${r.quantity}</td><td>${esc(r.candidate_id||'—')}</td><td>${fmt(r.score)}</td><td>${fmt(r.ocr_quantity)}</td><td>${fmt(r.quantity_confidence)}</td><td>${r.reward_corrected?'보상 수정 ':''}${r.quantity_corrected?'수량 수정':''}</td></tr>`))}<form id="admin-review"><div class="form-grid"><label>검토 상태<select name="status">${['unreviewed','accepted','duplicate','rejected'].map(x=>`<option ${x===s.review_status?'selected':''}>${x}</option>`).join('')}</select></label><label>검토 메모<input name="note" maxlength="500"></label></div><button>검토 저장</button></form><p class="hint">이미지 링크는 5분 후 만료됩니다. 상세 버튼을 다시 누르면 갱신됩니다.</p>${d.reviews.map(r=>`<p>${esc(r.created_at)} · ${esc(r.review_status)} · ${esc(r.note)}</p>`).join('')}</section>`;}
async function loadAdmin(more=false){try{adminBoss=$('#admin-boss').value.trim();adminReview=$('#admin-status').value;adminBefore=more&&adminRows.length?adminRows.at(-1).created_at:'';adminRows=(await api('admin-list',{boss:adminBoss,review_status:adminReview,before:adminBefore})).rows;adminDetail=null;render();}catch(e){toast(e.message,true);}}
function download(data,name,type){const url=URL.createObjectURL(new Blob([data],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function exportExcel(){
  const wb=XLSX.utils.book_new(),rows=summarize(state,rangeFrom,rangeTo||'9999-12-31');
  XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rows.map(r=>({'참여자':r.member,...Object.fromEntries([...EXCEL_COLUMNS,'합산가치'].map(k=>[k,r[k]]))}))), '개인장부');
  XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rows.map(r=>({'참여자':r.member,'보라가치':r.합산가치,'현금':r.현금,'수수료 제외':r['수수료 제외']}))), '전체정산');
  const raw=state.raids.filter(r=>r.date>=(rangeFrom||'')&&r.date<=(rangeTo||'9999-12-31')).flatMap(r=>r.rewards.map(x=>({'Raid ID':r.id,'날짜':r.date,'시간':r.time,'보스':r.boss,'참여자':r.member_ids.map(id=>state.members.find(m=>m.id===id)?.name).join(', '),'보상':x.reward_name,'수기 입력 단어':x.input_word||'','수량':x.quantity,'OCR수량':x.ocr_quantity,'인식점수':x.score,'후보ID':x.candidate_id,'수량신뢰도':x.quantity_confidence,'등급':x.rarity})));
  XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(raw),'원본기록');
  XLSX.writeFile(wb,`보스정산_${localDate()}.xlsx`);
}
function bind(){
  document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{if(busy){toast('인식이 완료된 후 이동해 주세요.');return;}tab=b.dataset.tab;render();});
  $('#screenshot')?.addEventListener('change',async e=>{
    const file=e.target.files[0];if(!file)return;if(file.size>20*1024*1024){toast('이미지는 20MB 이하로 선택해 주세요.',true);return;}
    busy=true;draft=[];sourceName=file.name;sourceFile=null;sourceCanvas=null;render();
    try{const canvas=await imageCanvas(file);if(canvas.width*canvas.height>40000000)throw Error('이미지 해상도가 너무 큽니다.');sourceFile=file;sourceCanvas=canvas;draft=await recognize(canvas,state,seed,text=>$('#progress').textContent=text);if(!draft.length)toast('카드를 찾지 못했습니다. 보상을 직접 추가해 주세요.',true);}
    catch(err){toast(err.message,true);busy=false;render();toast(err.message,true);return;}
    busy=false;render();toast(`${draft.length}개 카드 인식 완료. 보상과 수량을 확인해 주세요.`);
  });
  for(const [id,key] of [['raid-date','date'],['raid-time','time'],['raid-boss','boss'],['raid-memo','memo']])$(`#${id}`)?.addEventListener('change',e=>raidForm[key]=e.target.value);
  document.querySelectorAll('[data-member]').forEach(el=>el.onchange=()=>{raidForm.members=[...document.querySelectorAll('[data-member]:checked')].map(el=>Number(el.dataset.member));$('#member-count').textContent=`${raidForm.members.length}명 · 자동 균등 분배`;});
  document.querySelectorAll('[data-reward]').forEach(el=>el.onchange=()=>draft[el.dataset.reward].reward_id=el.value?Number(el.value):null);
  document.querySelectorAll('[data-qty]').forEach(el=>el.onchange=()=>draft[el.dataset.qty].quantity=el.value===''?NaN:Number(el.value));
  document.querySelectorAll('[data-remove]').forEach(el=>el.onclick=()=>{draft.splice(Number(el.dataset.remove),1);render();});
  $('#add-row')?.addEventListener('click',()=>{draft.push({reward_id:null,quantity:1});render();});
  $('#manual-reward-form')?.addEventListener('submit',e=>{e.preventDefault();if(busy||saving)return;const f=new FormData(e.target),word=String(f.get('word')||'').trim(),quantity=Number(f.get('quantity')),reward_id=Number(f.get('reward_id'));if(!word||!Number.isSafeInteger(quantity)||quantity<0||!state.rewards.find(r=>r.id===reward_id)?.enabled){toast('입력 단어, 정수 수량, 연결할 활성 보상을 확인해 주세요.',true);return;}draft.push({input_word:word,reward_id,quantity,candidate_id:null,score:null,ocr_quantity:null,quantity_confidence:null,match_status:'수기 입력 · 수동 매칭',quantity_status:'수기 수량'});render();toast('수기 보상을 추가했습니다. 정산 등록을 눌러 저장하세요.');});
  $('#save-raid')?.addEventListener('click',async()=>{
    if(!raidForm.members.length||raidForm.members.some(id=>!state.members.find(m=>m.id===id)?.active)){toast('활성 참여자를 1명 이상 선택해 주세요.',true);return;}
    if(!draft.length||draft.some(x=>!state.rewards.find(r=>r.id===x.reward_id)?.enabled||!Number.isFinite(x.quantity)||x.quantity<0)){toast('보상과 수량을 확인해 주세요. 미지정/비활성 보상은 등록할 수 없습니다.',true);return;}
    if(saving)return;
    if(session&&sourceFile&&!$('#collection-consent').checked){toast('원본 이미지 자동 제출 안내를 확인해 주세요.',true);return;}
    const raid={id:nextId(state.raids),client_record_id:crypto.randomUUID(),date:raidForm.date,time:raidForm.time,boss:raidForm.boss||state.bosses[0],memo:raidForm.memo,member_ids:[...raidForm.members],screenshot_name:sourceName,rewards:draft.map(({thumbnail,...r})=>({...r,reward_name:state.rewards.find(x=>x.id===r.reward_id).name,settlement_excluded:state.rewards.find(x=>x.id===r.reward_id).settlement_column==='__EXCLUDE__'}))};
    let job;
    try{if(session&&sourceFile){busy=true;const owner_id=session.user.id;render();const marked=await annotate(sourceCanvas,raid);const images=await Promise.all([{kind:'original',blob:sourceFile},{kind:'annotated',blob:marked}].map(async({kind,blob})=>({kind,sha256:await sha256(blob),mime:kind==='original'?sourceFile.type:'image/png',bytes:blob.size})));job={id:raid.client_record_id,owner_id,payload:collectionPayload(raid,seed,images,{width:sourceCanvas.width,height:sourceCanvas.height}),blobs:{original:sourceFile,annotated:marked},state:'pending',attempts:0,next:0};}const saved=await mutate(()=>{state.raids.push(raid);if(job)state.collection_notice=NOTICE_VERSION;},job);
    if(saved){draft=[];sourceName='';sourceFile=null;sourceCanvas=null;queue=await jobs();busy=false;render();toast(job?'정산 등록 완료 · 관리자에게 자동 전송합니다.':'정산 등록 완료 · 로컬 기록');pump(refreshCloud);}}
    catch(e){busy=false;render();toast(e.message,true);}finally{if(busy){busy=false;render();}}
  });
  $('#cloud-login')?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target),email=f.get('email'),password=f.get('password');try{const signup=e.submitter.value==='signup';const result=signup?await cloud.auth.signUp({email,password,options:{emailRedirectTo:base}}):await cloud.auth.signInWithPassword({email,password});if(result.error)throw result.error;toast(signup?'인증 메일을 보냈습니다. 이메일 인증 후 로그인해 주세요.':'로그인 완료');}catch(err){toast(err.message,true);}});
  $('#signout')?.addEventListener('click',()=>cloud.auth.signOut());
  $('#retry-cloud')?.addEventListener('click',async()=>{for(const j of await jobs())if(j.owner_id===session?.user.id&&j.state!=='complete')await putJob({...j,state:'pending',next:0});await refreshCloud();pump(refreshCloud);});
  $('#admin-refresh')?.addEventListener('click',()=>loadAdmin());$('#admin-more')?.addEventListener('click',()=>loadAdmin(true));
  document.querySelectorAll('[data-evidence]').forEach(b=>b.onclick=async()=>{try{adminDetail=await api('admin-evidence',{id:b.dataset.evidence});render();}catch(e){toast(e.message,true);}});
  $('#admin-review')?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target);try{await api('admin-review',{id:adminDetail.submission.id,review_status:f.get('status'),note:f.get('note')});adminDetail=await api('admin-evidence',{id:adminDetail.submission.id});render();toast('검토를 저장했습니다.');}catch(err){toast(err.message,true);}});
  $('#admin-export')?.addEventListener('click',()=>{const rows=adminRows.flatMap(s=>s.payload.rewards.map(r=>({'제출ID':s.id,'접수시각':s.created_at,'보스':s.payload.boss,'날짜':s.payload.date,'참여인원':s.payload.participant_count,'상태':s.status,'검토':s.review_status,...r})));const sheet=XLSX.utils.json_to_sheet(rows);download('\uFEFF'+XLSX.utils.sheet_to_csv(sheet),`수집기록_${localDate()}.csv`,'text/csv;charset=utf-8');});
  $('#filter')?.addEventListener('click',()=>{rangeFrom=$('#from').value;rangeTo=$('#to').value;if(rangeFrom&&rangeTo&&rangeFrom>rangeTo){toast('기간을 확인해 주세요.',true);return;}render();});
  $('#export-xlsx')?.addEventListener('click',exportExcel);
  $('#member-add')?.addEventListener('submit',e=>{e.preventDefault();mutate(()=>state.members.push({id:nextId(state.members),name:validateName(new FormData(e.target).get('name'),state.members),active:true}));});
  document.querySelectorAll('[data-save-member]').forEach(b=>b.onclick=()=>{const id=Number(b.dataset.saveMember),name=$(`[data-member-name="${id}"]`).value,active=$(`[data-member-active="${id}"]`).checked;mutate(()=>{const m=state.members.find(m=>m.id===id);m.name=validateName(name,state.members,id);m.active=active;});});
  document.querySelectorAll('[data-delete-member]').forEach(b=>b.onclick=()=>{const id=Number(b.dataset.deleteMember);if(confirm('선택 참여자를 영구 삭제할까요?'))mutate(()=>deleteMember(state,id));});
  document.querySelectorAll('[data-save-reward]').forEach(b=>b.onclick=()=>{const id=Number(b.dataset.saveReward),values={name:$(`[data-r-name="${id}"]`).value,unit_value:Number($(`[data-r-value="${id}"]`).value),quantity_mode:$(`[data-r-mode="${id}"]`).value,distribution_type:$(`[data-r-dist="${id}"]`).value,enabled:$(`[data-r-enabled="${id}"]`).checked};mutate(()=>{values.name=validateName(values.name,state.rewards,id);if(!Number.isFinite(values.unit_value)||values.unit_value<0)throw Error('값어치를 확인해 주세요.');Object.assign(state.rewards.find(r=>r.id===id),values);});});
  document.querySelectorAll('[data-delete-raid]').forEach(b=>b.onclick=async()=>{const raid=state.raids.find(r=>r.id===Number(b.dataset.deleteRaid));if(confirm('보스전 기록을 삭제하고 제출 기록도 철회할까요?')){const job=(await jobs()).find(j=>j.id===raid.client_record_id),withdrawal=job?{...job,replace:true,action:'withdraw',state:'pending',next:0,blobs:null}:undefined;if(await mutate(()=>state.raids=state.raids.filter(r=>r.id!==raid.id),withdrawal)){await refreshCloud();pump(refreshCloud);}}});
  $('#boss-add')?.addEventListener('submit',e=>{e.preventDefault();const name=new FormData(e.target).get('name').trim();mutate(()=>{if(!name||state.bosses.includes(name))throw Error('보스 이름이 비었거나 중복입니다.');state.bosses.push(name);});});
  $('#settings-form')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target);mutate(()=>state.settings={cash_per_100_value:Number(f.get('cash')),fee_rate:Number(f.get('fee')),match_threshold:Number(f.get('threshold'))});});
  $('#backup')?.addEventListener('click',()=>download(JSON.stringify(state,null,2),`cat_hero_backup_${localDate()}.json`,'application/json'));
  $('#restore')?.addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{const imported=validateState(JSON.parse(await file.text()),seed);if(confirm('현재 웹형 데이터를 백업 파일의 내용으로 교체할까요?'))mutate(()=>{state=imported;raidForm.members=state.members.filter(m=>m.active).slice(0,3).map(m=>m.id);draft=[];});}catch(err){toast(err.message,true);}});
}
async function init(){
  $('#app').innerHTML='<div class="loading">CAT HERO · 정산 데이터를 준비하고 있습니다.</div>';
  try{const response=await fetch(`${base}seed.json`);if(!response.ok)throw Error('기본 매핑을 불러오지 못했습니다.');seed=await response.json();state=structuredClone(seed);let warning;
    try{const stored=await readState(),saved=localStorage.getItem(KEY);if(stored)state=validateState(stored,seed);else if(saved){state=validateState(JSON.parse(saved),seed);await saveState(state);}}catch(err){warning=`저장 데이터 확인 필요: ${err.message}. 기존 저장본은 덮어쓰지 않았습니다.`;}
    for(const boss of seed.bosses)if(!state.bosses.includes(boss))state.bosses.push(boss);
    raidForm.members=state.members.filter(m=>m.active).slice(0,3).map(m=>m.id);raidForm.boss=state.bosses[0];await initCloud(()=>{adminRows=[];adminDetail=null;identity();});queue=await jobs();render();identity();if(warning)toast(warning,true);
  }catch(err){$('#app').innerHTML=`<div class="loading">${esc(err.message)}</div>`;}
}
window.addEventListener('online',()=>pump(refreshCloud));
setInterval(()=>pump(refreshCloud),15000);
init();
