import '@fontsource/noto-sans-kr/korean-400.css';
import '@fontsource/noto-sans-kr/korean-600.css';
import '@fontsource/noto-sans-kr/400.css';
import '@fontsource/noto-sans-kr/600.css';
import './style.css';
import * as XLSX from 'xlsx';
import {EXCEL_COLUMNS,summarize,validateName,deleteMember,validateState} from './domain.js';
import {imageCanvas,recognize} from './vision.js';
const KEY='cat-hero-boss-reward-v1',base=new URL(import.meta.env.BASE_URL, document.baseURI).href;
const $=s=>document.querySelector(s),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=x=>x===null||x===undefined?'—':Number(x).toLocaleString('ko-KR',{maximumFractionDigits:4});
const nextId=items=>Math.max(0,...items.map(x=>x.id))+1;
const localDate=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
let seed,state,tab='raid',draft=[],busy=false,sourceName='',rangeFrom='',rangeTo='';
let raidForm={date:localDate(),time:new Date().toTimeString().slice(0,5),boss:'',memo:'',members:[]};
const tabs=[['raid','보스전 등록','01'],['summary','정산 장부','02'],['records','보스전 기록','03'],['members','참여자 관리','04'],['rewards','보상 마스터','05'],['settings','설정 · 백업','06']];
function commit(){try{localStorage.setItem(KEY,JSON.stringify(state));}catch(e){throw Error('브라우저 저장 공간이 부족하거나 저장이 차단됐습니다. 백업을 내려받아 주세요.');}}
function mutate(fn){const before=structuredClone(state);try{fn();validateState(state,seed);commit();render();toast('저장했습니다.');return true;}catch(e){state=before;toast(e.message,true);return false;}}
function toast(text,error=false){const el=$('#toast');el.textContent=text;el.className=`toast visible ${error?'error':''}`;clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>el.classList.remove('visible'),6000);}
function table(headers,rows){return `<div class="table-scroll"><table><thead><tr>${headers.map(x=>`<th>${esc(x)}</th>`).join('')}</tr></thead><tbody>${rows.join('')||`<tr><td colspan="${headers.length}" class="empty">아직 데이터가 없습니다.</td></tr>`}</tbody></table></div>`;}
function render(){
  raidForm.members=raidForm.members.filter(id=>state.members.some(m=>m.id===id&&m.active));
  $('#app').innerHTML=`<aside><div class="brand"><span class="logo">C</span><div>CAT HERO<small>BOSS REWARD LEDGER</small></div></div><div class="nav-caption">WORKSPACE</div><nav>${tabs.map(([id,label,no])=>`<button data-tab="${id}" class="${tab===id?'selected':''}"><span>${no}</span>${label}</button>`).join('')}</nav><div class="aside-note"><span class="dot"></span>브라우저에 저장됨<p>이미지는 이 기기에서 처리합니다.<br>기기 간 이동은 JSON 백업으로.</p></div></aside>
  <main><header><div><div class="eyebrow">GUILD OPERATIONS / U01—U33</div><h1>${esc(tabs.find(t=>t[0]===tab)[1])}</h1></div><span class="badge">WEB EDITION · v1.1</span></header>
  <div class="mapping-note">픽뽑 · 픽업 → 전설픽업 &nbsp; / &nbsp; 룬 → 룬 소환 &nbsp; / &nbsp; 동 → 동료소환 &nbsp; / &nbsp; 빨레 · 보 → 정산 제외</div>
  <div id="content">${tab==='raid'?raidView():tab==='summary'?summaryView():tab==='records'?recordsView():tab==='members'?membersView():tab==='rewards'?rewardsView():settingsView()}</div>
  <footer>CAT HERO · 설치형과 같은 U01~U33 매핑 / 균등 분배 / 엑셀 환산 구조</footer></main><div id="toast" class="toast" role="status"></div>`;
  bind();
}
function raidView(){return `<section class="panel"><div class="section-heading"><h2>처치 기록</h2><span>STEP 01</span></div><div class="form-grid"><label>날짜<input id="raid-date" type="date" value="${esc(raidForm.date)}" required></label><label>시간<input id="raid-time" type="time" value="${esc(raidForm.time)}" required></label><label>보스<select id="raid-boss">${state.bosses.map(b=>`<option ${b===raidForm.boss?'selected':''}>${esc(b)}</option>`).join('')}</select></label><label>메모<input id="raid-memo" value="${esc(raidForm.memo)}" placeholder="선택 사항"></label></div><div class="section-heading participants"><h3>참여자</h3><span id="member-count">${raidForm.members.length}명 · 자동 균등 분배</span></div><div class="member-chips">${state.members.filter(m=>m.active).map(m=>`<label><input type="checkbox" data-member="${m.id}" ${raidForm.members.includes(m.id)?'checked':''}>${esc(m.name)}</label>`).join('')||'<p>참여자 관리에서 활성 참여자를 추가해 주세요.</p>'}</div></section>
  <section class="panel"><div class="section-heading"><h2>이미지 인식</h2><span>STEP 02</span></div><label class="upload-zone"><span class="upload-icon">＋</span><strong>처치 결과 스크린샷 선택</strong><span>PNG · JPG / 카드 검출 → 보상 매칭 → 숫자 인식</span><input id="screenshot" type="file" accept="image/png,image/jpeg" ${busy?'disabled':''}></label><p id="progress" class="status">${busy?'인식 중...':'템플릿 33개 연결 · 인식 후 보상과 수량을 확인해 주세요.'}</p>
  <div class="section-heading"><h3>인식 결과 확인 / 수정</h3><button id="add-row" class="secondary" ${busy?'disabled':''}>보상 직접 추가</button></div>
  ${table(['카드','보상','수량','OCR 수량','인식점수','후보ID','수량신뢰도','등급 / 상태',''],draft.map((r,i)=>`<tr><td>${r.thumbnail?`<img class="card-thumb" src="${r.thumbnail}" alt="카드 ${i+1}">`:'—'}</td><td><select data-reward="${i}" ${busy?'disabled':''}><option value="">미지정</option>${state.rewards.filter(x=>x.enabled||x.id===r.reward_id).map(x=>`<option value="${x.id}" ${x.id===r.reward_id?'selected':''}>${esc(x.name)}${x.enabled?'':' (비활성)'}</option>`).join('')}</select><small>후보: ${esc(r.candidate_name||'—')}</small></td><td><input type="number" min="0" step="1" value="${r.quantity}" data-qty="${i}" ${busy?'disabled':''}></td><td>${fmt(r.ocr_quantity)}</td><td>${r.score==null?'—':r.score.toFixed(3)}</td><td>${esc(r.candidate_id||'—')}</td><td>${r.quantity_confidence==null?'—':r.quantity_confidence.toFixed(3)}</td><td><span class="rarity ${esc(r.rarity)}">${esc(r.rarity||'수동')}</span><small>${esc(r.match_status||'직접 입력')}</small><small>${esc(r.quantity_status||'')}</small></td><td><button data-remove="${i}" class="danger quiet" ${busy?'disabled':''}>삭제</button></td></tr>`))}
  <div class="action-row"><span>${draft.length}개 보상 · ${esc(sourceName||'직접 입력 가능')}</span><button id="save-raid" ${busy?'disabled':''}>정산 등록</button></div></section>`;}
function summaryView(){const rows=summarize(state,rangeFrom,rangeTo||'9999-12-31'),value=rows.reduce((a,r)=>a+r.합산가치,0),cash=rows.reduce((a,r)=>a+r['수수료 제외'],0);return `<div class="metrics"><div><span>합산 보라가치</span><strong>${fmt(value)}</strong></div><div><span>수수료 제외 현금</span><strong>₩ ${fmt(cash)}</strong></div><div><span>정산 참여자</span><strong>${rows.length}<small>명</small></strong></div></div><section class="panel"><div class="section-heading"><h2>개인별 누적 장부</h2><button id="export-xlsx">Excel 다운로드</button></div><div class="date-range"><label>시작일<input id="from" type="date" value="${rangeFrom}"></label><label>종료일<input id="to" type="date" value="${rangeTo}"></label><button id="filter" class="secondary">기간 적용</button></div>${table(['참여자',...EXCEL_COLUMNS,'합산가치','현금','수수료 제외'],rows.map(r=>`<tr><td>${esc(r.member)}</td>${[...EXCEL_COLUMNS,'합산가치','현금','수수료 제외'].map(k=>`<td>${fmt(r[k])}</td>`).join('')}</tr>`))}<p class="hint">보상 값어치와 분배 방식 변경은 기존 기록의 합계에도 반영됩니다. 빨레/보는 기록에 보관하고 합산에서 제외합니다.</p></section>`;}
function recordsView(){return `<section class="panel"><div class="section-heading"><h2>원본 보스전 기록</h2><span>${state.raids.length} RAIDS</span></div>${table(['ID','날짜 / 시간','보스','참여자','보상 · 수량','메모',''],[...state.raids].reverse().map(r=>`<tr><td>#${r.id}</td><td>${esc(r.date)}<small>${esc(r.time)}</small></td><td>${esc(r.boss)}</td><td>${r.member_ids.map(id=>esc(state.members.find(m=>m.id===id)?.name)).join(', ')}</td><td>${r.rewards.map(x=>`${esc(x.reward_name)} × ${fmt(x.quantity)}`).join('<br>')}</td><td>${esc(r.memo)}</td><td><button class="danger quiet" data-delete-raid="${r.id}">삭제</button></td></tr>`))}</section>`;}
function membersView(){return `<section class="panel"><div class="section-heading"><h2>참여자 추가</h2><span>MEMBERS</span></div><form id="member-add" class="inline-form"><input name="name" placeholder="참여자 이름" required maxlength="80"><button>참여자 추가</button></form></section><section class="panel"><h2>참여자 관리</h2><p class="hint">비활성화하면 다음 보스전의 참여자 목록에서 제외됩니다. 기존 정산 기록은 유지됩니다.</p>${table(['ID','이름','상태',''],state.members.map(m=>`<tr><td>${m.id}</td><td><input data-member-name="${m.id}" value="${esc(m.name)}" maxlength="80"></td><td><label class="toggle"><input data-member-active="${m.id}" type="checkbox" ${m.active?'checked':''}>활성</label></td><td><button data-save-member="${m.id}" class="secondary">저장</button> <button data-delete-member="${m.id}" class="danger quiet">삭제</button></td></tr>`))}</section>`;}
function rewardsView(){return `<section class="panel"><div class="section-heading"><h2>보상 정보 / 값어치</h2><span>MASTER DATA</span></div><p class="hint">U01~U33 연결과 정산 컬럼은 고정합니다. 비활성 보상도 후보로 인식되며, 신규 정산에는 활성 보상만 등록할 수 있습니다.</p>${table(['보상명','정산 컬럼 / 후보ID','값어치','수량 방식','분배 방식','활성',''],state.rewards.map(r=>`<tr><td><input data-r-name="${r.id}" value="${esc(r.name)}" maxlength="80"></td><td>${esc(r.settlement_column==='__EXCLUDE__'?'정산 제외':r.settlement_column)}<small>${state.templates.filter(t=>t.reward_id===r.id).map(t=>esc(t.candidate_id)).join(' · ')}</small></td><td><input data-r-value="${r.id}" type="number" min="0" step="any" value="${r.unit_value}"></td><td><select data-r-mode="${r.id}">${['AUTO','OCR','DEFAULT_ONE'].map(m=>`<option ${m===r.quantity_mode?'selected':''}>${m}</option>`).join('')}</select></td><td><select data-r-dist="${r.id}">${['EQUAL','PER_PERSON'].map(m=>`<option value="${m}" ${m===r.distribution_type?'selected':''}>${m==='EQUAL'?'균등 분배':'인당 수량'}</option>`).join('')}</select></td><td><input data-r-enabled="${r.id}" type="checkbox" ${r.enabled?'checked':''}></td><td><button data-save-reward="${r.id}" class="secondary">저장</button></td></tr>`))}<p class="hint">소환권/랜덤 룬의 초기 값어치는 원본 프로젝트의 0을 유지했습니다. 필요하면 이 표에서 수정할 수 있습니다.</p></section>`;}
function settingsView(){return `<section class="panel"><h2>환산 / 인식 기준</h2><form id="settings-form"><div class="form-grid"><label>보라가치 100당 현금<input name="cash" type="number" min="0" step="any" value="${state.settings.cash_per_100_value}" required></label><label>수수료율 (0~1)<input name="fee" type="number" min="0" max="1" step="0.01" value="${state.settings.fee_rate}" required></label><label>자동매칭 기준 (0.50~0.99)<input name="threshold" type="number" min="0.5" max="0.99" step="0.01" value="${state.settings.match_threshold}" required></label></div><button>설정 저장</button></form></section><section class="panel"><h2>보스 추가</h2><form id="boss-add" class="inline-form"><input name="name" placeholder="새 보스 이름" required><button>보스 추가</button></form></section><section class="panel"><h2>데이터 백업 / 복원</h2><p>웹형 데이터는 현재 브라우저에 저장됩니다. 다른 기기에서는 JSON 백업을 불러와 이어서 사용하세요.</p><div class="backup-actions"><button id="backup">JSON 백업 다운로드</button><label class="file-button secondary">JSON 백업 복원<input id="restore" type="file" accept=".json,application/json"></label></div><p class="hint">복원은 현재 웹형 데이터를 교체합니다. 설치형 SQLite 데이터와 자동 동기화되지는 않습니다.</p><p class="hint">설치형은 저장소 ZIP을 내려받은 뒤 install.bat → run.bat 순서로 실행하세요. 기존 설치를 업데이트할 때 data/settlement.db를 먼저 백업하고 그대로 유지하세요.</p><a href="https://github.com/ryemso/cat_hero_boss_reward" target="_blank" rel="noopener">GitHub에서 설치형 받기 ↗</a></section>`;}
function download(data,name,type){const url=URL.createObjectURL(new Blob([data],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function exportExcel(){
  const wb=XLSX.utils.book_new(),rows=summarize(state,rangeFrom,rangeTo||'9999-12-31');
  XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rows.map(r=>({'참여자':r.member,...Object.fromEntries([...EXCEL_COLUMNS,'합산가치'].map(k=>[k,r[k]]))}))), '개인장부');
  XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rows.map(r=>({'참여자':r.member,'보라가치':r.합산가치,'현금':r.현금,'수수료 제외':r['수수료 제외']}))), '전체정산');
  const raw=state.raids.filter(r=>r.date>=(rangeFrom||'')&&r.date<=(rangeTo||'9999-12-31')).flatMap(r=>r.rewards.map(x=>({'Raid ID':r.id,'날짜':r.date,'시간':r.time,'보스':r.boss,'참여자':r.member_ids.map(id=>state.members.find(m=>m.id===id)?.name).join(', '),'보상':x.reward_name,'수량':x.quantity,'OCR수량':x.ocr_quantity,'인식점수':x.score,'후보ID':x.candidate_id,'수량신뢰도':x.quantity_confidence,'등급':x.rarity})));
  XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(raw),'원본기록');
  XLSX.writeFile(wb,`보스정산_${localDate()}.xlsx`);
}
function bind(){
  document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{if(busy){toast('인식이 완료된 후 이동해 주세요.');return;}tab=b.dataset.tab;render();});
  $('#screenshot')?.addEventListener('change',async e=>{
    const file=e.target.files[0];if(!file)return;if(file.size>20*1024*1024){toast('이미지는 20MB 이하로 선택해 주세요.',true);return;}
    busy=true;draft=[];sourceName=file.name;render();
    try{const canvas=await imageCanvas(file);draft=await recognize(canvas,state,seed,text=>$('#progress').textContent=text);if(!draft.length)toast('카드를 찾지 못했습니다. 보상을 직접 추가해 주세요.',true);}
    catch(err){toast(err.message,true);busy=false;render();toast(err.message,true);return;}
    busy=false;render();toast(`${draft.length}개 카드 인식 완료. 보상과 수량을 확인해 주세요.`);
  });
  for(const [id,key] of [['raid-date','date'],['raid-time','time'],['raid-boss','boss'],['raid-memo','memo']])$(`#${id}`)?.addEventListener('change',e=>raidForm[key]=e.target.value);
  document.querySelectorAll('[data-member]').forEach(el=>el.onchange=()=>{raidForm.members=[...document.querySelectorAll('[data-member]:checked')].map(el=>Number(el.dataset.member));$('#member-count').textContent=`${raidForm.members.length}명 · 자동 균등 분배`;});
  document.querySelectorAll('[data-reward]').forEach(el=>el.onchange=()=>draft[el.dataset.reward].reward_id=el.value?Number(el.value):null);
  document.querySelectorAll('[data-qty]').forEach(el=>el.onchange=()=>draft[el.dataset.qty].quantity=el.value===''?NaN:Number(el.value));
  document.querySelectorAll('[data-remove]').forEach(el=>el.onclick=()=>{draft.splice(Number(el.dataset.remove),1);render();});
  $('#add-row')?.addEventListener('click',()=>{draft.push({reward_id:null,quantity:1});render();});
  $('#save-raid')?.addEventListener('click',()=>{
    if(!raidForm.members.length||raidForm.members.some(id=>!state.members.find(m=>m.id===id)?.active)){toast('활성 참여자를 1명 이상 선택해 주세요.',true);return;}
    if(!draft.length||draft.some(x=>!state.rewards.find(r=>r.id===x.reward_id)?.enabled||!Number.isFinite(x.quantity)||x.quantity<0)){toast('보상과 수량을 확인해 주세요. 미지정/비활성 보상은 등록할 수 없습니다.',true);return;}
    const saved=mutate(()=>{state.raids.push({id:nextId(state.raids),date:raidForm.date,time:raidForm.time,boss:raidForm.boss||state.bosses[0],memo:raidForm.memo,member_ids:[...raidForm.members],screenshot_name:sourceName,rewards:draft.map(({thumbnail,...r})=>({...r,reward_name:state.rewards.find(x=>x.id===r.reward_id).name}))});});
    if(saved){draft=[];sourceName='';render();toast('정산 등록 완료');}
  });
  $('#filter')?.addEventListener('click',()=>{rangeFrom=$('#from').value;rangeTo=$('#to').value;if(rangeFrom&&rangeTo&&rangeFrom>rangeTo){toast('기간을 확인해 주세요.',true);return;}render();});
  $('#export-xlsx')?.addEventListener('click',exportExcel);
  $('#member-add')?.addEventListener('submit',e=>{e.preventDefault();mutate(()=>state.members.push({id:nextId(state.members),name:validateName(new FormData(e.target).get('name'),state.members),active:true}));});
  document.querySelectorAll('[data-save-member]').forEach(b=>b.onclick=()=>{const id=Number(b.dataset.saveMember),name=$(`[data-member-name="${id}"]`).value,active=$(`[data-member-active="${id}"]`).checked;mutate(()=>{const m=state.members.find(m=>m.id===id);m.name=validateName(name,state.members,id);m.active=active;});});
  document.querySelectorAll('[data-delete-member]').forEach(b=>b.onclick=()=>{const id=Number(b.dataset.deleteMember);if(confirm('선택 참여자를 영구 삭제할까요?'))mutate(()=>deleteMember(state,id));});
  document.querySelectorAll('[data-save-reward]').forEach(b=>b.onclick=()=>{const id=Number(b.dataset.saveReward),values={name:$(`[data-r-name="${id}"]`).value,unit_value:Number($(`[data-r-value="${id}"]`).value),quantity_mode:$(`[data-r-mode="${id}"]`).value,distribution_type:$(`[data-r-dist="${id}"]`).value,enabled:$(`[data-r-enabled="${id}"]`).checked};mutate(()=>{values.name=validateName(values.name,state.rewards,id);if(!Number.isFinite(values.unit_value)||values.unit_value<0)throw Error('값어치를 확인해 주세요.');Object.assign(state.rewards.find(r=>r.id===id),values);});});
  document.querySelectorAll('[data-delete-raid]').forEach(b=>b.onclick=()=>{if(confirm('보스전 기록을 삭제하고 정산을 다시 계산할까요?'))mutate(()=>state.raids=state.raids.filter(r=>r.id!==Number(b.dataset.deleteRaid)));});
  $('#boss-add')?.addEventListener('submit',e=>{e.preventDefault();const name=new FormData(e.target).get('name').trim();mutate(()=>{if(!name||state.bosses.includes(name))throw Error('보스 이름이 비었거나 중복입니다.');state.bosses.push(name);});});
  $('#settings-form')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target);mutate(()=>state.settings={cash_per_100_value:Number(f.get('cash')),fee_rate:Number(f.get('fee')),match_threshold:Number(f.get('threshold'))});});
  $('#backup')?.addEventListener('click',()=>download(JSON.stringify(state,null,2),`cat_hero_backup_${localDate()}.json`,'application/json'));
  $('#restore')?.addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{const imported=validateState(JSON.parse(await file.text()),seed);if(confirm('현재 웹형 데이터를 백업 파일의 내용으로 교체할까요?'))mutate(()=>{state=imported;raidForm.members=state.members.filter(m=>m.active).slice(0,3).map(m=>m.id);draft=[];});}catch(err){toast(err.message,true);}});
}
async function init(){
  $('#app').innerHTML='<div class="loading">CAT HERO · 정산 데이터를 준비하고 있습니다.</div>';
  try{const response=await fetch(`${base}seed.json`);if(!response.ok)throw Error('기본 매핑을 불러오지 못했습니다.');seed=await response.json();state=structuredClone(seed);let warning;
    try{const saved=localStorage.getItem(KEY);if(saved)state=validateState(JSON.parse(saved),seed);}catch(err){warning=`저장 데이터 확인 필요: ${err.message}. 기존 저장본은 덮어쓰지 않았습니다.`;}
    for(const boss of seed.bosses)if(!state.bosses.includes(boss))state.bosses.push(boss);
    raidForm.members=state.members.filter(m=>m.active).slice(0,3).map(m=>m.id);raidForm.boss=state.bosses[0];render();if(warning)toast(warning,true);
  }catch(err){$('#app').innerHTML=`<div class="loading">${esc(err.message)}</div>`;}
}
init();
